### PR TITLE
MediatR registered

### PR DESCRIPTION
**Pull request by jesp209i**
MediatR registered in IOC

### CODE REVIEW

**Review by mnabe — APPROVED** [review]
+1

**Comment by jesp209i** [comment]
In startup.cs I have added a reference to the Infrastructure project, which resolves the problem with the checks :)

**Comment by jesp209i** [comment]
I observed a probem with the docker database on my laptop, which I think is corrected now.
If you are having problems, please check if the for files in the `database/Dockerbuild` directory has Linux line endings (LF).
If your files has windows type line ending (CRLF), then you can change this in Visual Studio Code.
- Just ask if you have problems

**Comment by mnabe** [comment]
Docker-fejl
Jeg får denne besked, når jeg forsøger at køre run.bat (efter at have buildet). Jeg arbejder videre på at løse det, men venter med at merge til at jeg har fundet problemet.

**Comment by jesp209i** [comment]
Der må være en fejl med når den builder dit db-image til Docker.
Prøv at køre `build.bat` fra en kommandolinje
- hvordan ser output ud der?
- får du nogen åbenlyse fejl under build?

**Comment by mnabe** [comment]
@jesp209i Det var ganske rigtigt et lokalt problem. Løst nu - tak for hjælp!

**Review by mnabe — APPROVED** [review]
+1

**Pull request merged**
